FROM pgvector/pgvector:pg16

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-16-postgis-3 \
        postgresql-16-postgis-3-scripts && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
